### ISSUE TITLE
Unhandled Exception with Meshsplorer

### ISSUE THREAD

**Issue by bxbbllegumbxtch** [ME3Explorer/ME3Explorer#107]
This is really irritating and I can't find a solution anywhere. Help please!

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at KFreonLib.Scripting.ModMaker.GenerateMeshModJob(String newfile, Int32 expID, String pccname, Byte[] data) in C:\Users\mjperez\Documents\GitHubVisualStudio\ME3Explorer\KFreonLib\Scripting\ModMakerHelper.cs:line 1058
   at ME3Explorer.PCCEditor2.createBinaryReplaceJobFromObjectToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\mjperez\Documents\GitHubVisualStudio\ME3Explorer\ME3Explorer\PCCEditor2\PCCEditor2.cs:line 1146
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.100.0 built by: NETFXREL2STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

ME3Explorer
    Assembly Version: 1.1.721.684
    Win32 Version: 1.1.721.684
##     CodeBase: file:///C:/Program%20Files%20(x86)/EA%20Games/Mass%20Effect%203/ME3Explorer/ME3Explorer.exe

PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll

WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.91.0 built by: NETFXREL2STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

KFreonLib
    Assembly Version: 1.1.718.684
    Win32 Version: 1.1.718.684
##     CodeBase: file:///C:/Program%20Files%20(x86)/EA%20Games/Mass%20Effect%203/ME3Explorer/KFreonLib.DLL

PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll

System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll

Be.Windows.Forms.HexBox
    Assembly Version: 1.4.7.34520
    Win32 Version: 1.4.7.34520
##     CodeBase: file:///C:/Program%20Files%20(x86)/EA%20Games/Mass%20Effect%203/ME3Explorer/Be.Windows.Forms.HexBox.DLL

AmaroK86.MassEffect3.ZlibBlock
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/EA%20Games/Mass%20Effect%203/ME3Explorer/AmaroK86.MassEffect3.ZlibBlock.DLL

Gibbed.IO
    Assembly Version: 1.0.5764.34520
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/EA%20Games/Mass%20Effect%203/ME3Explorer/Gibbed.IO.DLL

System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by starkgate** [comment]
This site is reserved to bug reports ONLY, if you want help please post on the forum. If this is indeed a bug, also give details about how to reproduce it.

**Comment by rajasrijan** [comment]
@bxbbllegumbxtch +1
Every other click generates Unhandled Exception.
I reopen ME3Explorer after every change to texture/mesh, you can try that.

**Comment by KFreon** [comment]
Think this is fixed. Let me know in the newest release (726).
