### ISSUE TITLE
rev724 Unable to preview/fix texture

### ISSUE THREAD

**Issue by matsmith83** [ME3Explorer/ME3Explorer#124]
The following occurs when viewing/selecting a particular texture... 
![image](https://cloud.githubusercontent.com/assets/16199364/11977390/370b9608-a97a-11e5-8e6a-6c2e72eecd9a.png)

Sometimes I get the following when previewing...

Preview failed: Parameter is not valid.

If I try to 'Convert' it, I get a "Failed to extract texture for conversion" with the following in the DebugWindow...

**13:39:58:  File already exists.   System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\ME3Explorer\Exec\TPFToolsTemp\HMM_HVYa_Merc_Tint'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at SaltTPF.ZipReader.ZipEntryFull.Extract(Boolean Preview, String outname) in D:\My Documents\ME3Explorer\SaltTPF\ZipReader.cs:line 126
   at KFreonLib.Textures.TPFTexInfo.Extract(String ExtractPath, Boolean ToMemory) in D:\My Documents\ME3Explorer\KFreonLib\Textures\TexInfo.cs:line 607**

Using Autofix results in the following...

**13:40:48:  Fixing: HMM_HVYa_Merc_Tint
     FORMAT -> Current: DXT5  Expected: DXT5
     MIPS -> Current: 0  Expected: 9
13:40:48:  Error checking texture: Object reference not set to an instance of an object.**

I dont know if it's connected or relevant, but I also get the following error when opening the TPF...

**Error checking texture: Buffer size is not sufficient.**

I've extracted and posted the offending texture here...

http://1drv.ms/1m6DFk2

**Comment by matsmith83** [comment]
As of rev725 the MIPS are correctly detected, and the preview works.  However, it now seems to mis-detect the dimensions.

As you see above, the texture is detected as 512x512 in rev724.  In rev725 it's detected as 504x504 with a "DIMENSIONS" error.

**Comment by KFreon** [comment]
Oh hai 504x504. Long time no see...
Forgot to fix this when I updated the image engine. 
Fixed now :D
