### ISSUE TITLE
rev747, Texplorer ME2, Kfreon-requested bug

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#289]
@KFreon -- Tool threw an error at me when clicking on a specific texture. Looks like you specifically want to know about this one:

![me2liarace_exception](https://cloud.githubusercontent.com/assets/13645804/14251797/738f894e-fa39-11e5-9221-c6ee6a7d48e0.PNG)

---

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: LET ME KNOW ABOUT THIS! filename: F:\Origin Games\Mass Effect 3\BIOGame\DLC\DLC_OnlinePassHidCE\CookedPCConsole\SFXHenchImagesLiara_CE.pcc
   at KFreonLib.PCCObjects.ME3PCCObject..ctor(String filePath, Boolean TablesOnly) in D:\My Documents\ME3Explorer\KFreonLib\PCCObjects\ME3PCCObjectSALTPCC.cs:line 180
   at KFreonLib.PCCObjects.Creation.CreatePCCObject(String file, Int32 WhichGame) in D:\My Documents\ME3Explorer\KFreonLib\PCCObjects\PCCMisc.cs:line 35
   at KFreonLib.Textures.Creation.CreateTexture2D(String filename, Int32 expID, Int32 WhichGame, String pathBIOGame, UInt32 hash) in D:\My Documents\ME3Explorer\KFreonLib\Textures\Misc.cs:line 180
   at KFreonLib.Textures.Creation.CreateTexture2D(ITexture2D tex2D, Int32 WhichGame, String pathBIOGame) in D:\My Documents\ME3Explorer\KFreonLib\Textures\Misc.cs:line 194
   at ME3Explorer.Texplorer2.UpdateTexDetails(Int32 index, TreeTexInfo& tex, ITexture2D& tex2D) in D:\My Documents\ME3Explorer\ME3Explorer\Texplorer2.cs:line 1405
   at ME3Explorer.Texplorer2.MainListView_SelectedIndexChanged(Object sender, EventArgs e) in D:\My Documents\ME3Explorer\ME3Explorer\Texplorer2.cs:line 1622
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ME3Explorer
    Assembly Version: 1.2.747.0
    Win32 Version: 1.2.747.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/ME3Explorer.exe
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KFreonLib
    Assembly Version: 1.2.747.0
    Win32 Version: 1.2.747.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/KFreonLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 4.0.8.0
    Win32 Version: 4.0.8.14612
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/Newtonsoft.Json.DLL
----------------------------------------
UsefulThings
    Assembly Version: 1.5.6.0
    Win32 Version: 1.5.6.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/UsefulThings.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
CSharpImageLibrary
    Assembly Version: 3.1.4.0
    Win32 Version: 3.1.4.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/CSharpImageLibrary.EXE
----------------------------------------
AmaroK86.ImageFormat
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/AmaroK86.ImageFormat.DLL
----------------------------------------
Gibbed.IO
    Assembly Version: 1.0.5890.23746
    Win32 Version: 1.0.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/Gibbed.IO.DLL
----------------------------------------
AmaroK86.MassEffect3.ZlibBlock
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/AmaroK86.MassEffect3.ZlibBlock.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.0.518
    Win32 Version: 0.86.0.518
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r747/ME3Explorer/ICSharpCode.SharpZipLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by HuntersRun1** [comment]
Alright saw this issue and out of curiosity tested it myself. Strangely enough it works for me. I am able to select and enlarge the image. Note I believe my image is vanilla though. Also from what I gather that gui image is for mass effect 3 only. Apologies if I am just repeating what you already know.

**Comment by starkgate** [comment]
Thank you gift, I was starting to think we ran out of bugs to keep K occupied^^.

Not sure if this one is a bug though, it happened to me when I had to reinstall ME3 but kept my old trees. Regenerating the trees fixed it.

**Comment by ghost** [comment]
LOL, Creeper.

**Comment by alvarome** [comment]
Hi:

That was retty much the same issue -but with a different texture file- I had and was reported inside a previous bug report -when it was discovered that Texplorer and TPF/DDS tools were disabled due the initial DLC extraction window use-.

FWIW, so far was a problem at my end... I just restored -once more- my ME3 vanilla copy and the bug was gone. Usual suspect here a bad copied file, I think.

@giftfish Anyway, I´m still curious about that misterious "D:\MyDocuments..." path present in the exception text at the error window here... I received the same message but I have not such path in my system. Is it present in yours, Giftfish ?

Regards!
Alvaro

**Comment by starkgate** [comment]
@alvarome The 'D:\My Documents' path refers to files on KFreon's system. I don't think there's much to do about it, and it does no hurt either.

**Comment by ghost** [comment]
Nope, not present in mine, but looks like Creeper has already explained.

**Comment by KFreon** [comment]
I don't know why the path is shown that way. It must just be hardcoded into the files during build. 
Ultimately it's irrelevant since it isn't actually looking for something.

At this stage, that is a bug too since I can't remember why I put in that warning, but I knew it should never be seen.
 I'll take a look after work.

EDIT: Can do it at work since it was so easy. That path it shows there must be wrong. Can you find the pcc it's actually looking for?

**Comment by ghost** [comment]
@Kfreon -- This might be my bad.

I went to look up the PCC like you asked and saw that I had reverted the extracted DLC to the SFAR, during the process of testing.

I'm assuming that would cause this problem?

**Comment by SirCxyrtyx** [comment]
Yeah, that'll do it. Perhaps a more useful error message could be implemented instead of throwing an exception for this though?

**Comment by KFreon** [comment]
Yep that'll do it. 
Il throw in a more sensible message too.

**Comment by ghost** [comment]
Sorry about that, K. 

I saw the big, "LET ME KNOW ABOUT THIS", and didn't even think to troubleshoot >.<

**Comment by KFreon** [comment]
All good. Highlights a problem message :)

**Comment by Mgamerz** [comment]
During build it seems the paths are hard coded I to the debugging symbols. I think in release mode those are sanitized.

**Comment by ghost** [comment]
Now says "File not Found". Much better :)

Verified in rev748.
