### ISSUE TITLE
Beta 2.0.3 (bugs minor)  Sequence Editor - ShowMsg and SeqVarStr

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#362]
Cloned **BioSeqAct_ShowMessage.**

Added object into a sequence but it didn't show any input links.

Repeated and same thing happened.   It works fine in interpreter.

Cloned **BioSeqVar_StrRef** or **BioSeqVar_StrRefLiteral**

When adding to the sequence a exception message appeared as below.

Afterwards it seemed to work fine.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ME3Explorer.SequenceEditor.removeAllLinks(SBox obj)
   at ME3Explorer.SequenceEditor.addObjectsToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Thks.

**Comment by SirCxyrtyx** [comment]
Whoops. Forgot to check if something was a SeqVar before trying to strip links from it. That doesn't work for obvious reasons. Good catch on the BioSeqAct_SetMessage. It's base class wasn't being recognized as a sequence action during the database generation, so that bug affects quite a few BioSeqAct objects.

Thinking of pushing 2.0.4 once I fix this and a couple other github issues. Did you figure out what was going on with the size mismatches?

**Comment by Kinkojiro** [comment]
Unfortunately not.  I cannot replicate it, it seems random.   It seems to replicate the last few objects and doesn't create an offset change.  This trashed one file I was using but I always keep backups.

It maybe me using the toolkit incorrectly or something, but the programmer who is also helping me has had similar issues.

So go ahead and do 2.0.4 and I will continue to try to figure it out.   Thanks.
