### ISSUE TITLE
v3.0.0: Texplorer ME2 scan fails (LZO decompression failed)

### ISSUE THREAD

**Issue by GreatEmerald** [ME3Explorer/ME3Explorer#438]
Seems like issue #419 was not completely fixed after all, since in Stable v3.0.0 build I'm getting this error for every ME2 PCC file when scanning:

```
13:02:45:  Scanning PCC: C:\Program Files (x86)\Mass Effect 2\BioGame\CookedPC\BioD_BlbGtl.pcc failed. Reason: System.Exception: LZO decompression failed!
   at KFreonLib.Helpers.SaltLZOHelper.DecompressPCC(Stream raw, IPCCObject pcc)
   at KFreonLib.PCCObjects.ME2PCCObject.LoadHelper(MemoryStream tempStream)
   at KFreonLib.PCCObjects.ME2PCCObject..ctor(String path)
   at KFreonLib.PCCObjects.Creation.CreatePCCObject(String file, Int32 WhichGame)
   at ME3Explorer.Texplorer2.DeepScanPCC(String filename)
```

See the full Texplorer log here: [LZOError.txt](https://github.com/ME3Explorer/ME3Explorer/files/531800/LZOError.txt)

I'm using Windows 10, .NET Framework 4.6.2.

**Comment by SirCxyrtyx** [comment]
Odd, seems to work fine for me. Probably not the problem, but your ME3Explorer folder does have lzo2.dll and lzo2helper.dll in it right?

**Comment by GreatEmerald** [comment]
Yes. I "installed" it right from Releases of this repository. Strange.

Could it be that .NET 4.6.2 is doing something different from .NET 4.6.1, then?

**Comment by Eoxal** [comment]
Hey guys, just thought I'd let you know I'm having the same problem. I can supply the full log if wanted.

6:38:46 PM:  Scanning PCC: C:\Mass Effect\Mass Effect 2\BioGame\CookedPC\EntryMenu.pcc failed. Reason: System.Exception: LZO decompression failed!
   at KFreonLib.Helpers.SaltLZOHelper.DecompressPCC(Stream raw, IPCCObject pcc)
   at KFreonLib.PCCObjects.ME2PCCObject.LoadHelper(MemoryStream tempStream)
   at KFreonLib.PCCObjects.ME2PCCObject..ctor(String path)
   at KFreonLib.PCCObjects.Creation.CreatePCCObject(String file, Int32 WhichGame)
   at ME3Explorer.Texplorer2.DeepScanPCC(String filename)

**Comment by SirCxyrtyx** [comment]
Well, I installed 4.6.2 and it still works for me. This is most vexing. Could you try a couple things for me?

First, In ME3Explorer 3.0, could you open the Package Editor, and try opening one of the files that failed to  decompress in Texplorer  and tell me if that works.

Second, could you try doing a ME2 treescan with [ME3Explorer 2.0](https://github.com/ME3Explorer/ME3Explorer/releases/tag/r750) and tell me if that works?

**Comment by GreatEmerald** [comment]
Curious, neither of the two worked (nor opening packages in ME3Explorer 2.0 Package Editor).

<details>
  <summary>

ME3Explorer 3.0 Package Editor error log</summary>



```
  See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: LZO decompression failed!
   at ME3Explorer.Packages.CompressionHelper.DecompressME1orME2(Stream raw)
   at ME3Explorer.Packages.ME2Package..ctor(String path)
   at ME3Explorer.Packages.ME2Package.<>c.<Initialize>b__36_0(String f)
   at ME3Explorer.Packages.MEPackageHandler.OpenMEPackage(String pathToFile, WPFBase wpfWindow, WinFormsBase winForm)
   at ME3Explorer.WinFormsBase.LoadMEPackage(String s)
   at ME3Explorer.PackageEditor.LoadFile(String s)
   at ME3Explorer.PackageEditor.loadToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ME3Explorer
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/ME3Explorer.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
KFreonLib
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/KFreonLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///D:/ME2/ME3Explorer/Newtonsoft.Json.DLL
----------------------------------------
UsefulThings
    Assembly Version: 1.5.6.0
    Win32 Version: 1.5.6.0
    CodeBase: file:///D:/ME2/ME3Explorer/UsefulThings.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
HexConverter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/HexConverter.EXE
----------------------------------------
CSharpImageLibrary
    Assembly Version: 3.1.6.0
    Win32 Version: 3.1.6.0
    CodeBase: file:///D:/ME2/ME3Explorer/CSharpImageLibrary.EXE
----------------------------------------
Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///D:/ME2/ME3Explorer/Ionic.Zip.Reduced.DLL
----------------------------------------
ME3Creator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/ME3Creator.EXE
----------------------------------------
Microsoft.DirectX
    Assembly Version: 1.0.2902.0
    Win32 Version: 5.04.00.2904
    CodeBase: file:///D:/ME2/ME3Explorer/Microsoft.DirectX.DLL
----------------------------------------
UDKExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/UDKExplorer.EXE
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
Be.Windows.Forms.HexBox
    Assembly Version: 1.4.7.22568
    Win32 Version: 1.4.7.22568
    CodeBase: file:///D:/ME2/ME3Explorer/Be.Windows.Forms.HexBox.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Gibbed.IO
    Assembly Version: 1.0.6121.22568
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/Gibbed.IO.DLL
----------------------------------------
AmaroK86Lib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/ME3Explorer/AmaroK86Lib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

</details>

**Comment by SirCxyrtyx** [comment]
Damn. Well, I've still got a few ideas left fortunately. First, I'd like to rule out the possibility that we somehow have ME2 files that are in a slightly different format. Could you upload a file that causes the error?

Second, the "LZO Decompression Failed!" is a rather generic error, and it's obscuring whatever the real problem is. I've attached a build that should give a better error. Can you try using this build to open a file in the Package Editor and tell me what error it gives?
[ME3Explorer TestBuild for GreatEmerald.zip](https://github.com/ME3Explorer/ME3Explorer/files/543244/ME3Explorer.TestBuild.for.GreatEmerald.zip)

Thanks for all your help debugging this :+1:

**Comment by GreatEmerald** [comment]
I thought about it myself already, and did a few tests. First of all, scanning and opening PCCs that are already unpacked works fine. Then, using Gildor's decompress.exe tool with -lzo works to decompress the files that ME3Explorer can't open, and then the decompressed version can again be opened fine in ME3Explorer. So in theory I could just decompress all files manually and use that (but I'd rather not, since the partition I have ME2 installed on only has 10 GiB of space left). So looks like the format is not different, it's just the decompression not working for some reason... But sure, I'll upload a file to check anyway (along with the log from the test build) in the evening.

**Comment by GreatEmerald** [comment]
Huh, the error I get with the test build is quite interesting indeed:

<details>
<summary>

Test build error log</summary>



```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'lzo2helper.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ManagedLZO.LZO1X.LZODecompress(Byte[] srcBuf, UInt32 srcLen, Byte[] dstBuf, UInt32& dstLen)
   at ManagedLZO.LZO1X.Decompress(Byte[] src, Byte[] dst) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\Packages\MiniLZO.cs:line 73
   at ME3Explorer.Packages.CompressionHelper.DecompressME1orME2(Stream raw) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\Packages\CompressionHelper.cs:line 132
   at ME3Explorer.Packages.ME2Package..ctor(String path) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\Packages\ME2Package.cs:line 81
   at ME3Explorer.Packages.ME2Package.<>c.<Initialize>b__29_0(String f) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\Packages\ME2Package.cs:line 38
   at ME3Explorer.Packages.MEPackageHandler.OpenMEPackage(String pathToFile, WPFBase wpfWindow, WinFormsBase winForm) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\Packages\MEPackageHandler.cs:line 51
   at ME3Explorer.WinFormsBase.LoadMEPackage(String s) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\WinFormsBase.cs:line 34
   at ME3Explorer.PackageEditor.LoadFile(String s) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\PackageEditor\PackageEditor.cs:line 73
   at ME3Explorer.PackageEditor.loadToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\Image 17\Documents\GitHub\ME3Explorer\ME3Explorer\PackageEditor\PackageEditor.cs:line 62
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ME3Explorer
    Assembly Version: 3.0.0.1
    Win32 Version: 3.0.0.1
    CodeBase: file:///D:/ME2/Debug/ME3Explorer.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
KFreonLib
    Assembly Version: 3.0.0.1
    Win32 Version: 3.0.0.1
    CodeBase: file:///D:/ME2/Debug/KFreonLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///D:/ME2/Debug/Newtonsoft.Json.DLL
----------------------------------------
UsefulThings
    Assembly Version: 1.5.6.0
    Win32 Version: 1.5.6.0
    CodeBase: file:///D:/ME2/Debug/UsefulThings.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
HexConverter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/Debug/HexConverter.EXE
----------------------------------------
CSharpImageLibrary
    Assembly Version: 3.1.6.0
    Win32 Version: 3.1.6.0
    CodeBase: file:///D:/ME2/Debug/CSharpImageLibrary.EXE
----------------------------------------
Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///D:/ME2/Debug/Ionic.Zip.Reduced.DLL
----------------------------------------
ME3Creator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/Debug/ME3Creator.EXE
----------------------------------------
Microsoft.DirectX
    Assembly Version: 1.0.2902.0
    Win32 Version: 5.04.00.2904
    CodeBase: file:///D:/ME2/Debug/Microsoft.DirectX.DLL
----------------------------------------
UDKExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/Debug/UDKExplorer.EXE
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
Be.Windows.Forms.HexBox
    Assembly Version: 1.4.7.29199
    Win32 Version: 1.4.7.29199
    CodeBase: file:///D:/ME2/Debug/Be.Windows.Forms.HexBox.DLL
----------------------------------------
Gibbed.IO
    Assembly Version: 1.0.6133.29199
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/Debug/Gibbed.IO.DLL
----------------------------------------
AmaroK86Lib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ME2/Debug/AmaroK86Lib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

</details>

And indeed `lzo2helper.dll` is not listed as one of the loaded libraries (nor is it there in the previous log). So looks like Windows refuses to load the DLL file for some strange reason? I checked it, and originally it was listed as "blocked" due to being from the internet, I unblocked it and tried again, but the error was the same.

And here's the test file I used (from Gamestop DLC): [BioD_Nor_103Messages.pcc.zip](https://github.com/ME3Explorer/ME3Explorer/files/544782/BioD_Nor_103Messages.pcc.zip)

**Comment by GreatEmerald** [comment]
Hm, `lzo2.dll` and `lzo2helper.dll` are also the only two DLLs that are not marked as "Mono/.Net assembly" according to `file` ("PE32 executable (DLL) (GUI) Intel 80386, for MS Windows" instead of "PE32 executable (DLL) (console) Intel 80386, Mono/.Net assembly, for MS Windows"). Not sure if that is expected.

**Comment by jtaksas** [comment]
@GreatEmerald  - Have you tried running with the stable 2.0 release to see if you have the same issue? I found that I was having this issue as well yet it also occurred for 2.0, which made me believe that it is more system related than the 3.0 release itself. I found that uninstalling and reinstalling Visual C++ Redist, along with (although not ideal) replacing mvscr100.dll and mvscp110.dll for both 32 and 64 bit dll's into their respective windows folders fixed this issue for me. It may not be the solution for you, but running 2.0 should narrow whether it is the the application or the system.

**Comment by GreatEmerald** [comment]
@jtaksas Yes, in https://github.com/ME3Explorer/ME3Explorer/issues/438#issuecomment-254934268.
Hm, odd, but I could try it. Which redist do you mean?

**Comment by jtaksas** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=30679

I believe this is a requirement for me2controller. Following those installation steps I noticed that I was having issues with missing dll's around Erik-Js's binkw32 and figured that I might not have fully corrected the issue and that it could impact me3explorer

**Comment by GreatEmerald** [comment]
Oh yea, I'm pretty sure I installed that already for binkw32 as well.

**Comment by GreatEmerald** [comment]
Aha, it works now! Thanks @jtaksas for the suggestion. Apparently, specifically the 32-bit 2010 VC++ redistributable (`msvc*100.dll`) is needed for this.

So to solve this issue, either:
1. Ship the `msvc*100.dll` files in the archive
2. Recomplile `lzo2*.dll` to not require the DLLs
3. Add the 2010 redist as a requirement to the documentation and detect it in the first start wizard

**Comment by SirCxyrtyx** [comment]
Many thanks to both GreatEmerald and jtaksas for helping figure this out.
