### ISSUE TITLE
3.0.1, PackEd, End of Stream Error

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#472]
I'm still trying to isolate the cause of this, so I apologize for what I know will be an inadequate report. I expect the issue has something to do with the name list, and it may be related to Issue #469 or #471.

**Error message:**
![endofstream](https://cloud.githubusercontent.com/assets/13645804/24886678/20bed5fc-1e0b-11e7-833e-4381950ed767.PNG)

**Text:**
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Gibbed.IO.StreamHelpers.ReadBytes(Stream stream, Int32 length)
   at ME3Explorer.Packages.ME3ExportEntry..ctor(ME3Package pccFile, Stream stream)
   at ME3Explorer.Packages.ME3Package..ctor(String pccFilePath)
   at ME3Explorer.Packages.ME3Package.<>c.<Initialize>b__30_0(String f)
   at ME3Explorer.Packages.MEPackageHandler.OpenMEPackage(String pathToFile, WPFBase wpfWindow, WinFormsBase winForm)
   at ME3Explorer.WinFormsBase.LoadMEPackage(String s)
   at ME3Explorer.PackageEditor.LoadFile(String s)
   at ME3Explorer.PackageEditor.loadToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

ME3Explorer
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/ME3Explorer.exe

PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll

PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll

System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll

KFreonLib
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/KFreonLib.DLL

Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/Newtonsoft.Json.DLL

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

UsefulThings
    Assembly Version: 1.5.6.0
    Win32 Version: 1.5.6.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/UsefulThings.DLL

HexConverter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/HexConverter.EXE

CSharpImageLibrary
    Assembly Version: 3.1.6.0
    Win32 Version: 3.1.6.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/CSharpImageLibrary.EXE

Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/Ionic.Zip.Reduced.DLL

ME3Creator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/ME3Creator.EXE

Microsoft.DirectX
    Assembly Version: 1.0.2902.0
    Win32 Version: 5.04.00.2904
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.DirectX/1.0.2902.0__31bf3856ad364e35/Microsoft.DirectX.dll

UDKExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/UDKExplorer.EXE

PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll

PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll

PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll

PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll

PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll

UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll

UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

Gibbed.IO
    Assembly Version: 1.0.6133.29199
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/Gibbed.IO.DLL

AmaroK86Lib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/AmaroK86Lib.DLL

ICSharpCode.SharpZipLib
    Assembly Version: 0.86.0.518
    Win32 Version: 0.86.0.518
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/ICSharpCode.SharpZipLib.DLL

Piccolo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/Piccolo.DLL

Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll

Be.Windows.Forms.HexBox
    Assembly Version: 1.4.7.29199
    Win32 Version: 1.4.7.29199
    CodeBase: file:///H:/Modding/ME3Explorer%20Dev/Current%20Beta/ME3Explorer/Be.Windows.Forms.HexBox.DLL

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Logger output:**
`ME3Log - Logging started.
ULinkerLoad::operator<<, Bad name index 2927/1342, Archive ..\..\BIOGame\DLC\DLC_MOD_TMLORE\CookedPCConsole\BioD_ThaMod_001Thane.pcc`

---

This error is strange and reminds me of one of the bugs in the Conditional Editor a long time ago. PackEd will not throw the error until you **re-open** the file. You can keep the file open and mod it all afternoon (like I did), and the toolset is fine. However, the game knows the problem is there and the logger will show the output above when you try to load the file in game (and the game will hang). Once you re-load or re-open the file in PackEd, then it will throw the error window.

As far as what could be causing it, I didn't deal with that many objects or operations, so the list is relatively small:

- Cloning animsequences within/across files and from ME2>ME3
- Cloning bioanimsetdata ME2>ME3
- Cloning biodynamicanimset within/across files (ME3 only) 
- Cloning packages within/across files and from ME2>ME3
- Editing properties for animsequence, bioanimsetdata, biodynamicanimset
- Editing binary data for biodynamicanimset, animsequence
- Adding new properties to BodySMC
- Editing BodySMC properties
- Adding/editing names

One of these operations (or, well, I guess it could be a combination) results in the error. Since I suspect it has something to do with the name list, I'll do some additional testing tomorrow and see if I can narrow the field a bit.

**Comment by ghost** [comment]
I have a bit more information on this, but it seems to be a **very** strange bug. 

After further testing this morning, this seems to be an issue related to order of operations or the file contents not refreshing when it should. 

I just ran a series of tests doing this and only this:

**TEST 1**
- Clone a ME2 package, within the ME2 file
- Clone that package into ME3
- Clone an animsequence from ME2 to ME3
- Clone a bioanimsetdata from ME2 to ME3
- Clone two import classes from one ME3 file to another
- Relink metadata for all cloned in exports
- Fix one property reference on the animsequence export, so it properly points to the new bioanimsetdata export
- Save File

**Results:** File can't be reloaded, PackEd throws error upon reload, game hangs when it tries to load file.

To ensure the problem wasn't due to the hex edit necessary to make the ME2 animsequence compatible with ME3, I then did that edit and reloaded. Same problem.

I kept this edit as simple as possible, with no name changes or additions. I also didn't actually finish the edit and didn't link the new animations to any stuntactor. So, there shouldn't have been any type of functionality issue, in game. These would merely be new objects in the file that wouldn't actually be used.

---

I then started over. New copy of the file and re-did all these steps, piecemeal, in the following order:

**TEST 2**
- Clone a ME2 package, within the ME2 file
- Clone that package into ME3
- Relink
- Save
**Results:**  File okay in PackEd and Game. No errors.

**TEST 3**
- Add bioanimsetdata import class from one ME3 file to another
- Save
**Results:**  File okay in PackEd and Game. No errors.

**TEST 4**
- Clone a bioanimsetdata from ME2 to ME3
- Relink
- Save
**Results:**  File okay in PackEd and Game. No errors.

**TEST 5**
- Add animsequence import class from one ME3 file to another
- Save
**Results:**  File okay in PackEd and Game. No errors.

**TEST 6**
- Clone an animsequence from ME2 to ME3
- Relink
- Fix one property reference on this object, so it properly points to the new bioanimsetdata export
- Save
**Results:**  File okay in PackEd and Game. No errors.

**TEST 7**
- Hex edit animsequence export to create compatibility with ME3
- Save
**Results: File okay in PackEd and Game. No errors.**

**At this point, the collective edits in TEST 2-7 are identical to everything I did in TEST 1.**

---

This series of tests suggests there are one of two problems:

1. New bioanimsetdata must be cloned in before their related animsequences. 
2. The act of **Saving** when doing one or more of these operations above is necessary to retaining the integrity of the file. When not saved, succeeding operations will not work properly, despite the tool failing to notify the user otherwise.

Number one above seems unlikely, but is one of the differences between the two sets of tests. My bet is on number two. I don't know which action(s) it is, and I'm **very** surprised that I've never run into the problem before.

@Kinkojiro, do you have any further insights on this that might help @SirCxyrtyx ?
